import { test, expect } from 'vitest';
import { expectStaticTypeError, ok, evaluated } from '../harness.mts';

// #sec-narrowto: a narrowing whose result admits no value is ~empty~: a pair of
// parameterizations whose governing meta type's `meet` answers null (#table-meta-hooks),
// or a comparison whose `narrow` leaves an empty range (#sec-metadata-decomposition).
// A test with such a result can never succeed (#sec-narrowfrom).

test.each([
  "type NB = { bounds?: RangeBounds.<any> }; meta NB { default = {}; validate(value, c) { return c.bounds === undefined || c.bounds.contains(value); } subtype(a,b) { if (b.bounds === undefined) return true; if (a.bounds === undefined) return false; return b.bounds.contains(a.bounds); } meet(a,b) { if (a.bounds === undefined) return b; if (b.bounds === undefined) return a; const r = a.bounds.intersect(b.bounds); return r.isEmpty ? null : { bounds: r }; } narrow(cur, op, val) { if (cur.bounds === undefined) return cur; if (op === \">\") return { bounds: cur.bounds.intersect((val + 1)..) }; if (op === \"<\") return { bounds: cur.bounds.intersect(..<val) }; return cur; } } primitive uint8 { operator uint8.<NB>() { return this; } } function f(x: uint8.<{ bounds: 0..=10 }>) { if (x is uint8.<{ bounds: 20..=30 }>) {} }",
  "type NB = { bounds?: RangeBounds.<any> }; meta NB { default = {}; validate(value, c) { return c.bounds === undefined || c.bounds.contains(value); } subtype(a,b) { if (b.bounds === undefined) return true; if (a.bounds === undefined) return false; return b.bounds.contains(a.bounds); } meet(a,b) { if (a.bounds === undefined) return b; if (b.bounds === undefined) return a; const r = a.bounds.intersect(b.bounds); return r.isEmpty ? null : { bounds: r }; } narrow(cur, op, val) { if (cur.bounds === undefined) return cur; if (op === \">\") return { bounds: cur.bounds.intersect((val + 1)..) }; if (op === \"<\") return { bounds: cur.bounds.intersect(..<val) }; return cur; } } primitive uint8 { operator uint8.<NB>() { return this; } } function f(x: uint8.<{ bounds: 0..=10 }>) { if (x > 20) {} }",
])("a test the meet proves empty is refused: %s", expectStaticTypeError);

test.each([
  "type NB = { bounds?: RangeBounds.<any> }; meta NB { default = {}; validate(value, c) { return c.bounds === undefined || c.bounds.contains(value); } subtype(a,b) { if (b.bounds === undefined) return true; if (a.bounds === undefined) return false; return b.bounds.contains(a.bounds); } meet(a,b) { if (a.bounds === undefined) return b; if (b.bounds === undefined) return a; const r = a.bounds.intersect(b.bounds); return r.isEmpty ? null : { bounds: r }; } narrow(cur, op, val) { if (cur.bounds === undefined) return cur; if (op === \">\") return { bounds: cur.bounds.intersect((val + 1)..) }; if (op === \"<\") return { bounds: cur.bounds.intersect(..<val) }; return cur; } } primitive uint8 { operator uint8.<NB>() { return this; } } function f(x: uint8.<{ bounds: 0..=10 }>) { if (x > 5) { let y: uint8.<{ bounds: 6..=10 }> = x; } } 'ok';",
  "type NB = { bounds?: RangeBounds.<any> }; meta NB { default = {}; validate(value, c) { return c.bounds === undefined || c.bounds.contains(value); } subtype(a,b) { if (b.bounds === undefined) return true; if (a.bounds === undefined) return false; return b.bounds.contains(a.bounds); } meet(a,b) { if (a.bounds === undefined) return b; if (b.bounds === undefined) return a; const r = a.bounds.intersect(b.bounds); return r.isEmpty ? null : { bounds: r }; } narrow(cur, op, val) { if (cur.bounds === undefined) return cur; if (op === \">\") return { bounds: cur.bounds.intersect((val + 1)..) }; if (op === \"<\") return { bounds: cur.bounds.intersect(..<val) }; return cur; } } primitive uint8 { operator uint8.<NB>() { return this; } } function f(x: uint8.<{ bounds: 0..=10 }>) { if (x is uint8.<{ bounds: 5..=30 }>) {} } 'ok';",
])("a test the meet leaves inhabited is accepted: %s", (source) => expect(ok(source)).toBe(true));
